# CAC40_COMPANIES = [
#     {"name": "Air Liquide", "ticker": "AI.PA"},
#     {"name": "Airbus", "ticker": "AIR.PA"},
#     {"name": "Alstom", "ticker": "ALO.PA"},
#     {"name": "ArcelorMittal", "ticker": "MT.AS"},
#     {"name": "Axa", "ticker": "CS.PA"},
#     {"name": "BNP Paribas", "ticker": "BNP.PA"},
#     {"name": "Bouygues", "ticker": "EN.PA"},
#     {"name": "Capgemini", "ticker": "CAP.PA"},
#     {"name": "Carrefour", "ticker": "CA.PA"},
#     {"name": "Dassault Systèmes", "ticker": "DSY.PA"},
#     {"name": "Engie", "ticker": "ENGI.PA"},
#     {"name": "EssilorLuxottica", "ticker": "EL.PA"},
#     {"name": "Hermès", "ticker": "RMS.PA"},
#     {"name": "Kering", "ticker": "KER.PA"},
#     {"name": "Legrand", "ticker": "LR.PA"},
#     {"name": "L'Oréal", "ticker": "OR.PA"},
#     {"name": "LVMH", "ticker": "MC.PA"},
#     {"name": "Michelin", "ticker": "ML.PA"},
#     {"name": "Orange", "ticker": "ORA.PA"},
#     {"name": "Pernod Ricard", "ticker": "RI.PA"},
#     {"name": "Publicis", "ticker": "PUB.PA"},
#     {"name": "Renault", "ticker": "RNO.PA"},
#     {"name": "Safran", "ticker": "SAF.PA"},
#     {"name": "Saint-Gobain", "ticker": "SGO.PA"},
#     {"name": "Sanofi", "ticker": "SAN.PA"},
#     {"name": "Schneider Electric", "ticker": "SU.PA"},
#     {"name": "Société Générale", "ticker": "GLE.PA"},
#     {"name": "STMicroelectronics", "ticker": "STMPA.PA"},
#     {"name": "Téléperformance", "ticker": "TEP.PA"},
#     {"name": "Thales", "ticker": "HO.PA"},
#     {"name": "TotalEnergies", "ticker": "TTE.PA"},
#     {"name": "Unibail-Rodamco-Westfield", "ticker": "URW.PA"},
#     {"name": "Veolia", "ticker": "VIE.PA"},
#     {"name": "Vinci", "ticker": "DG.PA"},
#     {"name": "Vivendi", "ticker": "VIV.PA"},
#     {"name": "Worldline", "ticker": "WLN.PA"},
#     {"name": "Eurofins Scientific", "ticker": "ERF.PA"},
#     {"name": "Dassault Aviation", "ticker": "AM.PA"},
#     {"name": "Edenred", "ticker": "EDEN.PA"},
# ]

CAC40_COMPANIES = [
{"name": "Accor", "ticker": "AC.PA"},
{"name": "AB Science", "ticker": "AB.PA"},  
{"name": "ABC Arbitrage", "ticker": "ABCA.PA"},
{"name": "Adocia", "ticker": "ADOC.PA"},
{"name": "ADP (Aéroports de Paris)", "ticker": "ADP.PA"},
{"name": "Air France – KLM", "ticker": "AF.PA"},
{"name": "Air Liquide", "ticker": "AI.PA"},
{"name": "Airbus", "ticker": "AIR.PA"},
{"name": "Akwel", "ticker": "AKW.PA"},
{"name": "Alstom", "ticker": "ALO.PA"},
{"name": "Altarea", "ticker": "ALTA.PA"},
{"name": "Alten", "ticker": "ATE.PA"},
{"name": "Amundi", "ticker": "AMUN.PA"},
{"name": "Argan", "ticker": "ARG.PA"},
{"name": "Arkema", "ticker": "AKE.PA"},
{"name": "Artmarket.com", "ticker": "PRC.PA"},
{"name": "Assystem", "ticker": "ASY.PA"},
{"name": "Aubay", "ticker": "AUB.PA"},
{"name": "Avenir Telecom", "ticker": "AVT.PA"},
{"name": "AXA", "ticker": "CS.PA"},
{"name": "Ayvens", "ticker": "AYV.PA"},
{"name": "Bains de Mer Monaco", "ticker": "BAIN.PA"},
{"name": "Believe", "ticker": "BLV.PA"},
{"name": "Beneteau", "ticker": "BEN.PA"},
{"name": "BIC", "ticker": "BB.PA"},
{"name": "BigBen Interactive", "ticker": "BIG.PA"},
{"name": "bioMérieux", "ticker": "BIM.PA"},
{"name": "BNP Paribas", "ticker": "BNP.PA"},
{"name": "Boiron", "ticker": "BOI.PA"},
{"name": "Bolloré", "ticker": "BOL.PA"},
{"name": "Bonduelle", "ticker": "BON.PA"},
{"name": "Bouygues", "ticker": "EN.PA"},
{"name": "Bureau Veritas", "ticker": "BVI.PA"},
{"name": "Capgemini", "ticker": "CAP.PA"},
{"name": "Carmila", "ticker": "CARM.PA"},
{"name": "Carrefour", "ticker": "CA.PA"},
{"name": "Casino Guichard", "ticker": "CO.PA"},
{"name": "Catana Group", "ticker": "ALCAT.PA"},
{"name": "Cegedim", "ticker": "CGM.PA"},
{"name": "Christian Dior", "ticker": "CDI.PA"},
{"name": "Claranova", "ticker": "CLA.PA"},
{"name": "Clariene", "ticker": "CLARI.PA"},
{"name": "Coface", "ticker": "COFA.PA"},
{"name": "Compagnie de l’Odet", "ticker": "ODET.PA"},
{"name": "Compagnie de Chargeurs Invest", "ticker": "CRI.PA"},
{"name": "Covivio", "ticker": "COV.PA"},
{"name": "Covivio Hotels", "ticker": "COVH.PA"},
{"name": "Crédit Agricole SA", "ticker": "ACA.PA"},
{"name": "Crit", "ticker": "CEN.PA"},
{"name": "Danone", "ticker": "BN.PA"},
{"name": "Dassault Aviation", "ticker": "AM.PA"},
{"name": "Dassault Systèmes", "ticker": "DSY.PA"},
{"name": "DBV Technologies", "ticker": "DBV.PA"},
{"name": "DMS", "ticker": "ALDMS.PA"},
{"name": "Edenred", "ticker": "EDEN.PA"},
{"name": "Eiffage", "ticker": "FGR.PA"},
{"name": "Ekinops", "ticker": "EKI.PA"},
{"name": "Elior Group", "ticker": "ELIOR.PA"},
{"name": "Elis", "ticker": "ELIS.PA"},
{"name": "Emeis (ex Orpea)", "ticker": "EMEIS.PA"},
{"name": "Engie", "ticker": "ENGI.PA"},
{"name": "Equasens", "ticker": "EQUA.PA"},
{"name": "Eramet", "ticker": "ERA.PA"},
{"name": "EssilorLuxottica", "ticker": "EL.PA"},
{"name": "Eurazeo", "ticker": "RF.PA"},
{"name": "Euroapi", "ticker": "EAPI.PA"},
{"name": "Eurofins Scientific", "ticker": "ERF.PA"},
{"name": "Euronext", "ticker": "ENX.PA"},
{"name": "Europacorp", "ticker": "ALECP.PA"},
{"name": "Eutelsat", "ticker": "ETL.PA"},
{"name": "Exail Technologies", "ticker": "EXA.PA"},
{"name": "Exel Industries A", "ticker": "EXE.PA"},
{"name": "FDJ United", "ticker": "FDJU.PA"},
{"name": "Financière Moncey", "ticker": "FMONC.PA"},
{"name": "Fnac Darty", "ticker": "FNAC.PA"},
{"name": "Forvia (ex Faurecia)", "ticker": "FRVIA.PA"},
{"name": "Gecina", "ticker": "GFC.PA"},
{"name": "Genfit", "ticker": "GNFT.PA"},
{"name": "Getlink (ex Eurotunnel)", "ticker": "GET.PA"},
{"name": "GL Events", "ticker": "PIG.PA"},
{"name": "GTT (Gaztransport et Technigaz)", "ticker": "GTT.PA"},
{"name": "Haulotte Group", "ticker": "HOT.PA"},
{"name": "Hermès International", "ticker": "RMS.PA"},
{"name": "Hexaom", "ticker": "ALHEX.PA"},
{"name": "Icade", "ticker": "ICAD.PA"},
{"name": "ID Logistics", "ticker": "IDL.PA"},
{"name": "Imerys", "ticker": "NK.PA"},
{"name": "Innate Pharma", "ticker": "IPH.PA"},
{"name": "Interparfums", "ticker": " ITP.PA"},
{"name": "Ipsen", "ticker": "IPN.PA"},
{"name": "Ipsos", "ticker": "IPS.PA"},
{"name": "Jacquet Metals", "ticker": "JCQ.PA"},
{"name": "JCDecaux", "ticker": "DEC.PA"},
{"name": "Kering", "ticker": "KER.PA"},
{"name": "Klépierre", "ticker": "LI.PA"},
{"name": "L'Oréal", "ticker": "OR.PA"},
{"name": "Lagardère SA", "ticker": "MMB.PA"},
{"name": "Lectra", "ticker": "LSS.PA"},
{"name": "Legrand", "ticker": "LR.PA"},
{"name": "LNA Santé", "ticker": "LNA.PA"},
{"name": "Lumibird", "ticker": "LBIRD.PA"},
{"name": "LVMH", "ticker": "MC.PA"},
{"name": "M6 Métropole Télévision", "ticker": "MMT.PA"},
{"name": "Manitou BF", "ticker": "MTU.PA"},
{"name": "Marie Brizard", "ticker": "MBWS.PA"},
{"name": "Maroc Telecom", "ticker": "IAM.PA"},
{"name": "Maurel & Prom", "ticker": "MAU.PA"},
{"name": "Mercialys", "ticker": "MERY.PA"},
{"name": "Mersen", "ticker": "MRN.PA"},
{"name": "Michelin", "ticker": "ML.PA"},
{"name": "Nanobiotix", "ticker": "NANO.PA"},
{"name": "Neurones", "ticker": "NRO.PA"},
{"name": "Nexans", "ticker": "NEX.PA"},
{"name": "Nexity", "ticker": "NXI.PA"},
{"name": "Nokia", "ticker": "NOK"},
{"name": "Oeneo", "ticker": "SBT.PA"},
{"name": "OPMobility", "ticker": "OPM.PA"},
{"name": "Orange", "ticker": "ORA.PA"},
{"name": "OSE Immunotherapeutics", "ticker": "OSE.PA"},
{"name": "OVHcloud", "ticker": "OVH.PA"},
{"name": "Pernod Ricard", "ticker": "RI.PA"},
{"name": "Peugeot Invest", "ticker": "PEUG.PA"},
{"name": "Phaxiam Therapeutics", "ticker": "PHXM.PA"},
{"name": "Pierre et Vacances", "ticker": "VAC.PA"},
{"name": "Plastivaloire", "ticker": "PVL.PA"},
{"name": "Prologue", "ticker": "ALPRG.PA"},
{"name": "Publicis Groupe", "ticker": "PUB.PA"},
{"name": "Quadient", "ticker": "QDT.PA"},
{"name": "Rallye", "ticker": "RAL.PA"},
{"name": "Ramsay Générale", "ticker": "RMS.PA"},
{"name": "Rémy Cointreau", "ticker": "RCO.PA"},
{"name": "Renault", "ticker": "RNO.PA"},
{"name": "Rexel", "ticker": "RXL.PA"},
{"name": "Rubis", "ticker": "RUI.PA"},
{"name": "Safran", "ticker": "SAF.PA"},
{"name": "Saint-Gobain", "ticker": "SGO.PA"},
{"name": "Sanofi", "ticker": "SAN.PA"},
{"name": "Sartorius Stedim Biotech", "ticker": "DIM.PA"},
{"name": "Savencia", "ticker": "SAVE.PA"},
{"name": "Schneider Electric", "ticker": "SU.PA"},
{"name": "Scor", "ticker": "SCR.PA"},
{"name": "SEB", "ticker": "SK.PA"},
{"name": "Sèche Environnement", "ticker": "VIE.PA"},
{"name": "SES", "ticker": "SESG.PA"},
{"name": "Société Générale", "ticker": "GLE.PA"},
{"name": "Société LDC", "ticker": "SAF.PA"},
{"name": "Sodexo", "ticker": "SW.PA"},
{"name": "Soitec", "ticker": "SOI.PA"},
{"name": "Solocal Group", "ticker": "LOCAL.PA"},
{"name": "Solutions 30", "ticker": "S30.PA"},
{"name": "Sopra Steria", "ticker": "SOP.PA"},
{"name": "Spie", "ticker": "SPIE.PA"},
{"name": "Stef", "ticker": "STF.PA"},
{"name": "Stellantis", "ticker": "STLAP.PA"},
{"name": "STMicroelectronics", "ticker": "STMPA.PA"},
{"name": "Sword Group", "ticker": "SWP.PA"},
{"name": "Synergie", "ticker": "SDG.PA"},
{"name": "Technip Energies", "ticker": "TE.PA"},
{"name": "Teleperformance", "ticker": "TEP.PA"},
{"name": "TF1", "ticker": "TFI.PA"},
{"name": "TFF Group", "ticker": "TFF.PA"},
{"name": "Thales", "ticker": "HO.PA"},
{"name": "Tikehau Capital", "ticker": "TKO.PA"},
{"name": "TotalEnergies", "ticker": "TTE.PA"},
{"name": "Tour Eiffel", "ticker": "EIFF.PA"},
{"name": "Trigano", "ticker": "TRI.PA"},
{"name": "Ubisoft", "ticker": "UBI.PA"},
{"name": "Valeo", "ticker": "FR.PA"},
{"name": "Valerios Therapeutics (ex Onxeo)", "ticker": "ALVAL.PA"},
{"name": "Vallourec", "ticker": "VK.PA"},
{"name": "Valneva", "ticker": "VLA.PA"},
{"name": "Veolia", "ticker": "VIE.PA"},
{"name": "Verallia", "ticker": "VRLA.PA"},
{"name": "Verimatrix", "ticker": "VMX.PA"},
{"name": "Vetoquinol", "ticker": "VETO.PA"},
{"name": "Vicat", "ticker": "VCT.PA"},
{"name": "Vinci", "ticker": "DG.PA"},
{"name": "Virbac", "ticker": "VIRP.PA"},
{"name": "Voltalia", "ticker": "VLTSA.PA"},
{"name": "Vranken-Pommery", "ticker": "VRAP.PA"},
{"name": "VusionGroup", "ticker": "VU.PA"},
{"name": "Wavestone", "ticker": "WAVE.PA"},
{"name": "Wendel", "ticker": "MF.PA"},
{"name": "Worldline", "ticker": "WLN.PA"},
{"name": "2CRSI", "ticker": "AL2SI.PA"},
{"name": "Wallix", "ticker": "ALLIX.PA"},
{"name": "Parrot", "ticker": "PARRO.PA"},
{"name": "Lighton", "ticker": "ALTAI.PA"},
]
